import React from 'react';
import { Sparkles, Lightbulb, Zap, Target } from 'lucide-react';

export function EmptyState() {
  const features = [
    {
      icon: Sparkles,
      title: 'AI-Powered',
      description: 'Get unique, brandable names generated by advanced AI',
    },
    {
      icon: Zap,
      title: 'Instant Results',
      description: 'See available domains and social handles in seconds',
    },
    {
      icon: Target,
      title: 'Industry-Specific',
      description: 'Tailored suggestions for your specific market',
    },
  ];

  return (
    <div className="bg-white rounded-xl border border-gray-200 shadow-sm p-12">
      <div className="max-w-2xl mx-auto text-center">
        {/* Illustration */}
        <div className="mb-8 flex justify-center">
          <div className="relative">
            <div className="w-32 h-32 bg-gradient-to-br from-slate-100 to-blue-100 rounded-full flex items-center justify-center">
              <Lightbulb className="w-16 h-16 text-slate-600" />
            </div>
            <div className="absolute -top-2 -right-2 w-12 h-12 bg-gradient-to-br from-slate-700 to-slate-900 rounded-full flex items-center justify-center">
              <Sparkles className="w-6 h-6 text-white" />
            </div>
          </div>
        </div>

        {/* Heading */}
        <h2 className="text-2xl mb-3 text-gray-900">
          Ready to Find Your Perfect Brand Name?
        </h2>
        <p className="text-gray-600 mb-8 max-w-lg mx-auto">
          Describe your product or idea above, and our AI will generate unique, memorable names with
          available domains and social handles.
        </p>

        {/* Features Grid */}
        <div className="grid md:grid-cols-3 gap-6 mt-8">
          {features.map((feature, index) => (
            <div key={index} className="text-center">
              <div className="w-12 h-12 bg-slate-100 rounded-xl flex items-center justify-center mx-auto mb-3">
                <feature.icon className="w-6 h-6 text-slate-700" />
              </div>
              <h3 className="text-sm font-semibold text-gray-900 mb-1">{feature.title}</h3>
              <p className="text-sm text-gray-600">{feature.description}</p>
            </div>
          ))}
        </div>

        {/* Tips */}
        <div className="mt-8 pt-8 border-t border-gray-200">
          <p className="text-sm text-gray-500 mb-3">
            💡 <span className="font-medium">Pro tip:</span> Be specific about your product, target
            audience, and key features for better results.
          </p>
        </div>
      </div>
    </div>
  );
}
